server:
	cp .env.example .env
	composer install
	php artisan key:generate
	nano .env
	php artisan serve

conf-git-filipe:
	git config --global user.name "filipeandrev"
	git config --global user.email "filipe.andrev7@gmail.com"

conf-git-leonardo:
	git config --global user.name "leonardolfp"
	git config --global user.email "leonardolfp15@gmail.com"

conf-git-aline:
        git config --global user.name "alinevenceslau"
        git config --global user.email "alineepecris79@gmail.com"

